py_library(
	name = 'sql_connection',
	srcs = ['sql_connection.py'],
	visibility = ["//visibility:public"],

)

py_library(
	name = 'sql_tables',
	srcs = ['sql_tables.py'],
	deps = [':sql_connection'],
	visibility = ["//visibility:public"],
)