py_library(
	name = 'mongodb',
	srcs = ['mongodb.py'],
	visibility = ["//visibility:public"],
)

py_library(
	name = 'mongo_collections',
	srcs = ['mongo_collections.py'],
	deps = [':mongodb'],
    visibility = ["//visibility:public"],
)